apiVersion: apps/v1
kind: Deployment
metadata:
  name: extra-ingredient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extra-ingredient
  template:
    metadata:
      labels:
        app: extra-ingredient
    spec:
      containers:
        - name: extra-ingredient
          image: 076161/heaven-extra-ingredient
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://extra-ingredient-mongo-srv:27017/extra-ingredient"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: extra-ingredient-srv
spec:
  selector:
    app: extra-ingredient
  ports:
    - name: extra-ingredient
      protocol: TCP
      port: 4002
      targetPort: 4002
