apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredient
  template:
    metadata:
      labels:
        app: ingredient
    spec:
      containers:
        - name: ingredient
          image: 076161/heaven-ingredient
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://ingredient-mongo-srv:27017/ingredient"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: ingredient-srv
spec:
  selector:
    app: ingredient
  ports:
    - name: ingredient
      protocol: TCP
      port: 4003
      targetPort: 4003
