apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /user(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /seller(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: seller-srv
                port:
                  number: 5000
          - path: /order(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-srv
                port:
                  number: 4000
          - path: /ingredient(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ingredient-srv
                port:
                  number: 12000
          - path: /modifier-group(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: option-srv
                port:
                  number: 4006
          - path: /extra-ingredient(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: extra-ingredient-srv
                port:
                  number: 4002
          - path: /product(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-srv
                port:
                  number: 4007
          - path: /category(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: category-srv
                port:
                  number: 4001
          - path: /promotion(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: promotion-srv
                port:
                  number: 4008
