apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
        - name: kitchen
          image: 076161/heaven-kitchen
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://kitchen-mongo-srv:27017/kitchen"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen-srv
spec:
  selector:
    app: kitchen
  ports:
    - name: kitchen
      protocol: TCP
      port: 4005
      targetPort: 4005
