apiVersion: apps/v1
kind: Deployment
metadata:
  name: option-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: option
  template:
    metadata:
      labels:
        app: option
    spec:
      containers:
        - name: option
          image: 076161/heaven-option
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://option-mongo-srv:27017/option"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4006
---
apiVersion: v1
kind: Service
metadata:
  name: option-srv
spec:
  selector:
    app: option
  ports:
    - name: option
      protocol: TCP
      port: 4006
      targetPort: 4006
