apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller
  template:
    metadata:
      labels:
        app: seller
    spec:
      containers:
        - name: seller
          image: 076161/heaven-seller
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://seller-mongo-srv:27017/seller"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: seller-srv
spec:
  selector:
    app: seller
  ports:
    - name: seller
      protocol: TCP
      port: 5000
      targetPort: 5000
