apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tip
  template:
    metadata:
      labels:
        app: tip
    spec:
      containers:
        - name: tip
          image: 076161/heaven-tip
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://tip-mongo-srv:27017/tip"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4010
---
apiVersion: v1
kind: Service
metadata:
  name: tip-srv
spec:
  selector:
    app: tip
  ports:
    - name: tip
      protocol: TCP
      port: 4010
      targetPort: 4010
