apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiter-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waiter
  template:
    metadata:
      labels:
        app: waiter
    spec:
      containers:
        - name: waiter
          image: 076161/heaven-waiter
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://waiter-mongo-srv:27017/waiter"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4011
---
apiVersion: v1
kind: Service
metadata:
  name: waiter-srv
spec:
  selector:
    app: waiter
  ports:
    - name: waiter
      protocol: TCP
      port: 4011
      targetPort: 4011
